#!/usr/bin/env python3
"""
DOLPHLINK CMS Builder
=====================

Converts the CSV files in this folder into ../content/content.json,
which is consumed by js/main.js at runtime.

Usage:
    python cms/build.py            # rebuild content.json from CSVs
    python cms/build.py --check    # verify CSVs are valid without writing

Files read:
    text.csv         flat key=value pairs (dotted keys, e.g. hero.eyebrow)
    menu.csv         nav menu items (label, scrollTo, href, target)
    stats.csv        4 reliability cards
    portfolios.csv   6 portfolio buttons
    audit.csv        4 audit boxes
    sectors.csv      9 chart sectors
    locations.csv    12 map locations

File written:
    ../content/content.json
"""

from __future__ import annotations

import csv
import io
import json
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent
OUT = ROOT.parent / "content" / "content.json"
COMMENT = (
    "Auto-generated by cms/build.py from the CSVs in /cms. "
    "DO NOT edit by hand — edit the CSVs and rerun: python cms/build.py"
)


# -------------------------------------------------------------- helpers
def read_csv(name: str) -> list[dict[str, str]]:
    """Read a CSV tolerantly:
    - strips UTF-8 BOM (Excel adds this)
    - falls back to UTF-16 if Excel saved as 'CSV UTF-16'
    - removes stray NUL bytes (from corrupted saves or filesystem caches)
    - skips fully-blank rows
    """
    path = ROOT / name
    if not path.exists():
        raise FileNotFoundError(f"Missing CSV: {path}")
    raw = path.read_bytes()
    # UTF-16 LE/BE BOM detection
    if raw.startswith((b"\xff\xfe", b"\xfe\xff")):
        text = raw.decode("utf-16")
    else:
        text = raw.decode("utf-8-sig", errors="replace")
    # Strip stray NULs (Excel/legacy encoder artifacts)
    text = text.replace("\x00", "")
    reader = csv.DictReader(io.StringIO(text))
    return [r for r in reader if any((v or "").strip() for v in r.values())]


def set_path(obj: dict[str, Any], dotted: str, value: Any) -> None:
    """Assign value into obj at the dotted path, creating intermediate dicts."""
    parts = dotted.split(".")
    cur = obj
    for k in parts[:-1]:
        cur = cur.setdefault(k, {})
    cur[parts[-1]] = value


def to_bool(s: str) -> bool:
    return str(s).strip().lower() in {"true", "1", "yes", "y", "t"}


def to_float(s: str, field: str, row: int) -> float:
    try:
        return float(s)
    except ValueError as e:
        raise ValueError(f"locations.csv row {row}: '{field}' is not a number ({s!r})") from e


# -------------------------------------------------------------- builder
def build() -> dict[str, Any]:
    out: dict[str, Any] = {"_comment": COMMENT}

    # 1. Flat key/value strings
    for row in read_csv("text.csv"):
        key = (row.get("key") or "").strip()
        if not key or key.startswith("#"):
            continue
        set_path(out, key, row.get("value") or "")

    # 2. Nav menu items (variable count — add/remove rows in menu.csv)
    out.setdefault("nav", {})
    out["nav"]["menuItems"] = [
        {
            "label":    r["label"],
            "scrollTo": (r.get("scrollTo") or "").strip(),
            "href":     (r.get("href") or "").strip(),
            "target":   (r.get("target") or "").strip(),
        }
        for r in read_csv("menu.csv")
    ]

    # 3. Reliability stats (4 cards)
    out.setdefault("reliability", {})
    out["reliability"]["stats"] = [
        {
            "key":   r["key"].strip(),
            "icon":  r["icon"].strip(),
            "value": r["value"],
            "label": r["label"],
            "desc":  r["desc"],
        }
        for r in read_csv("stats.csv")
    ]

    # 4. Portfolio items (6 buttons)
    out.setdefault("portfolios", {})
    out["portfolios"]["items"] = [
        {
            "key":   r["key"].strip(),
            "icon":  r["icon"].strip(),
            "label": r["label"],
            "desc":  r["desc"],
        }
        for r in read_csv("portfolios.csv")
    ]

    # 5. Audit boxes (4)
    out.setdefault("audit", {})
    out["audit"]["items"] = [
        {"title": r["title"], "desc": r["desc"]} for r in read_csv("audit.csv")
    ]

    # 6. Chart sectors (9)
    out.setdefault("charts", {})
    out["charts"]["sectors"] = [
        {"name": r["name"], "color": r["color"], "desc": r["desc"]}
        for r in read_csv("sectors.csv")
    ]

    # 7. Map locations (12)
    out["charts"]["locations"] = [
        {
            "name":  r["name"],
            "value": [to_float(r["lng"], "lng", i + 2), to_float(r["lat"], "lat", i + 2)],
            "isHQ":  to_bool(r["isHQ"]),
        }
        for i, r in enumerate(read_csv("locations.csv"))
    ]

    return out


# -------------------------------------------------------------- main
def main() -> int:
    check_only = "--check" in sys.argv
    try:
        data = build()
    except Exception as e:
        print(f"❌ Build failed: {e}", file=sys.stderr)
        return 1

    text = json.dumps(data, indent=2, ensure_ascii=False) + "\n"

    if check_only:
        print("✓ All CSVs parsed successfully")
        print(f"  reliability.stats   {len(data['reliability']['stats'])}")
        print(f"  portfolios.items    {len(data['portfolios']['items'])}")
        print(f"  audit.items         {len(data['audit']['items'])}")
        print(f"  charts.sectors      {len(data['charts']['sectors'])}")
        print(f"  charts.locations    {len(data['charts']['locations'])}")
        return 0

    # Atomic write — write to temp then rename so a crash won't corrupt content.json
    OUT.parent.mkdir(parents=True, exist_ok=True)
    tmp = OUT.with_suffix(".json.tmp")
    tmp.write_text(text, encoding="utf-8")
    tmp.replace(OUT)

    rel = OUT.relative_to(ROOT.parent)
    print(f"✓ Wrote {rel} ({len(text)} bytes)")
    print("  Reload your browser — Live Server picks up the change automatically.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
